name = "theapp"
type = "webpack"
account_id = "a808e3483344308a7ff8d5ed2b7a2930"
workers_dev = true
webpack_config = "./webpack.config.js"
compatibility_date = "2021-10-10"

[site]
bucket = "./dist/client"
entry-point = "./worker"
